//
// Generated file, do not edit! Created by opp_msgtool 6.3 from flood/FloodPacket.msg.
//

#ifndef __FLOOD_FLOODPACKET_M_H
#define __FLOOD_FLOODPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace flood {

class FloodPacket;
class FloodHello;

}  // namespace flood

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

// cplusplus {{
using namespace inet;
// }}


namespace flood {

/**
 * Class generated from <tt>flood/FloodPacket.msg:11</tt> by opp_msgtool.
 * <pre>
 * class FloodPacket extends inet::FieldsChunk
 * {
 *     uint32_t src;
 *     uint32_t dst;
 *     uint32_t lastHop;
 *     uint32_t packetId;
 *     uint8_t hopLimit;
 *     uint8_t hopStart;
 *     bool wantAck;
 *     uint64_t txTimeNs;
 *     string payload;
 * }
 * </pre>
 */
class FloodPacket : public ::inet::FieldsChunk
{
  protected:
    uint32_t src = 0;
    uint32_t dst = 0;
    uint32_t lastHop = 0;
    uint32_t packetId = 0;
    uint8_t hopLimit = 0;
    uint8_t hopStart = 0;
    bool wantAck = false;
    uint64_t txTimeNs = 0;
    ::omnetpp::opp_string payload;

  private:
    void copy(const FloodPacket& other);

  protected:
    bool operator==(const FloodPacket&) = delete;

  public:
    FloodPacket();
    FloodPacket(const FloodPacket& other);
    virtual ~FloodPacket();
    FloodPacket& operator=(const FloodPacket& other);
    virtual FloodPacket *dup() const override {return new FloodPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual uint32_t getSrc() const;
    virtual void setSrc(uint32_t src);

    virtual uint32_t getDst() const;
    virtual void setDst(uint32_t dst);

    virtual uint32_t getLastHop() const;
    virtual void setLastHop(uint32_t lastHop);

    virtual uint32_t getPacketId() const;
    virtual void setPacketId(uint32_t packetId);

    virtual uint8_t getHopLimit() const;
    virtual void setHopLimit(uint8_t hopLimit);

    virtual uint8_t getHopStart() const;
    virtual void setHopStart(uint8_t hopStart);

    virtual bool getWantAck() const;
    virtual void setWantAck(bool wantAck);

    virtual uint64_t getTxTimeNs() const;
    virtual void setTxTimeNs(uint64_t txTimeNs);

    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FloodPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FloodPacket& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>flood/FloodPacket.msg:24</tt> by opp_msgtool.
 * <pre>
 * class FloodHello extends inet::FieldsChunk
 * {
 *     uint32_t src;
 *     uint32_t neighbours[];
 *     uint32_t mprs[];
 * }
 * </pre>
 */
class FloodHello : public ::inet::FieldsChunk
{
  protected:
    uint32_t src = 0;
    uint32_t *neighbours = nullptr;
    size_t neighbours_arraysize = 0;
    uint32_t *mprs = nullptr;
    size_t mprs_arraysize = 0;

  private:
    void copy(const FloodHello& other);

  protected:
    bool operator==(const FloodHello&) = delete;

  public:
    FloodHello();
    FloodHello(const FloodHello& other);
    virtual ~FloodHello();
    FloodHello& operator=(const FloodHello& other);
    virtual FloodHello *dup() const override {return new FloodHello(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual uint32_t getSrc() const;
    virtual void setSrc(uint32_t src);

    virtual void setNeighboursArraySize(size_t size);
    virtual size_t getNeighboursArraySize() const;
    virtual uint32_t getNeighbours(size_t k) const;
    virtual void setNeighbours(size_t k, uint32_t neighbours);
    virtual void insertNeighbours(size_t k, uint32_t neighbours);
    [[deprecated]] void insertNeighbours(uint32_t neighbours) {appendNeighbours(neighbours);}
    virtual void appendNeighbours(uint32_t neighbours);
    virtual void eraseNeighbours(size_t k);

    virtual void setMprsArraySize(size_t size);
    virtual size_t getMprsArraySize() const;
    virtual uint32_t getMprs(size_t k) const;
    virtual void setMprs(size_t k, uint32_t mprs);
    virtual void insertMprs(size_t k, uint32_t mprs);
    [[deprecated]] void insertMprs(uint32_t mprs) {appendMprs(mprs);}
    virtual void appendMprs(uint32_t mprs);
    virtual void eraseMprs(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FloodHello& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FloodHello& obj) {obj.parsimUnpack(b);}


}  // namespace flood


namespace omnetpp {

template<> inline flood::FloodPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<flood::FloodPacket*>(ptr.get<cObject>()); }
template<> inline flood::FloodHello *fromAnyPtr(any_ptr ptr) { return check_and_cast<flood::FloodHello*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __FLOOD_FLOODPACKET_M_H

